name: "Fetch Codes"

on:
  schedule:
    - cron: "0 0/6 * * *"
  workflow_dispatch:

jobs:
  fetch-codes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Dependencies
        run: |
          corepack enable
          yarn install

      - name: Fetch codes
        run: |
          yarn scrape

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update redeem codes
